import { useState } from 'react';
import { useSyncExternalStore } from 'react';
import { ChevronDown } from 'lucide-react';
import {
  Portfolio, portfolioMetrics, portfolioEquity, portfolioActions,
  getPState, subscribePortfolio,
} from '@/lib/portfolio-store';
import { contractPnl } from '@/lib/portfolio-math';
import PortfolioCloseModal from './PortfolioCloseModal';

interface Props {
  prices: Record<string, number>;
}

export default function PortfolioTrackerCard({ prices }: Props) {
  const pstate = useSyncExternalStore(subscribePortfolio, getPState, getPState);
  if (pstate.portfolios.length === 0) return null;

  return (
    <div className="space-y-2">
      {pstate.portfolios.map(p => (
        <PortfolioCard key={p.id} portfolio={p} prices={prices} />
      ))}
    </div>
  );
}

function PortfolioCard({ portfolio, prices }: { portfolio: Portfolio; prices: Record<string, number> }) {
  const [expanded, setExpanded] = useState(true);
  const [closeMode, setCloseMode] = useState<'partial' | 'full' | null>(null);
  const m = portfolioMetrics(portfolio, prices);
  const isDone = portfolio.status !== 'active';
  const targetProgress = m.targetPayout > 0
    ? Math.max(0, Math.min(100, (m.aggPnl / m.targetPayout) * 100)) : 0;

  const statusColor = portfolio.status === 'liquidated' ? 'text-destructive'
    : portfolio.status === 'closed' ? 'text-muted-foreground'
    : m.aggPnl >= 0 ? 'text-accent' : 'text-destructive';

  return (
    <div className={`bg-card border rounded-lg overflow-hidden ${
      portfolio.status === 'liquidated' ? 'border-destructive/60'
      : portfolio.status === 'closed' ? 'border-border'
      : 'border-gold/40'
    }`}>
      {/* Header */}
      <button
        onClick={() => setExpanded(e => !e)}
        className="w-full px-3 py-2 flex items-center justify-between hover:bg-secondary/30 transition-colors"
      >
        <div className="flex-1 min-w-0 text-left">
          <div className="flex items-center gap-1.5">
            <span className={`text-[8px] uppercase tracking-widest font-bold ${
              portfolio.status === 'liquidated' ? 'text-destructive'
              : portfolio.status === 'closed' ? 'text-muted-foreground'
              : 'text-gold'
            }`}>
              {portfolio.status === 'active' ? 'Portfolio' : portfolio.status}
            </span>
            <span className="text-[10px] font-mono font-bold text-foreground truncate">{portfolio.name}</span>
          </div>
          <div className="text-[8px] font-mono text-muted-foreground mt-0.5">
            {portfolio.contracts.length} contracts · margin ${portfolio.margin}
          </div>
        </div>
        <div className="text-right">
          <div className={`text-[12px] font-mono font-black tabular-nums ${statusColor}`}>
            ${m.equity.toFixed(2)}
          </div>
          <div className={`text-[8px] font-mono ${m.aggPnl >= 0 ? 'text-accent' : 'text-destructive'}`}>
            {m.aggPnl >= 0 ? '+' : ''}${m.aggPnl.toFixed(2)}
          </div>
        </div>
        <ChevronDown className={`w-3.5 h-3.5 ml-2 text-muted-foreground transition-transform ${expanded ? 'rotate-180' : ''}`} />
      </button>

      {expanded && (
        <div className="border-t border-border p-2 space-y-2">
          {/* Top-line stats: Live vs Target */}
          <div className="grid grid-cols-2 gap-1.5">
            <BigStat label="Live Portfolio Value" value={`$${m.liveValue.toFixed(2)}`} sub="Current value generated by reality evolution" tone={m.aggPnl >= 0 ? 'accent' : 'destructive'} />
            <BigStat label="Target Portfolio Payout" value={`+$${m.targetPayout.toFixed(2)}`} sub="Maximum intended outcome under current conviction" tone="gold" />
          </div>

          {/* Progress to target */}
          {portfolio.status === 'active' && m.targetPayout > 0 && (
            <div>
              <div className="flex items-center justify-between text-[8px] uppercase tracking-wider text-muted-foreground mb-0.5">
                <span>Progress to Target</span>
                <span className="text-foreground font-mono">{targetProgress.toFixed(0)}%</span>
              </div>
              <div className="h-1.5 bg-secondary rounded overflow-hidden">
                <div className="h-full bg-gold transition-all" style={{ width: `${Math.max(0, targetProgress)}%` }} />
              </div>
            </div>
          )}

          {/* Metrics row */}
          <div className="grid grid-cols-4 gap-1 text-[9px] font-mono">
            <Mini label="Health" value={`${(m.health * 100).toFixed(0)}%`} />
            <Mini label="Eff. Lev" value={`${m.effLeverage.toFixed(1)}x`} />
            <Mini label="Exposure" value={`$${m.activeExposure.toFixed(0)}`} />
            <Mini label="Liq Buf" value={`$${m.liqBuffer.toFixed(0)}`} />
          </div>

          {/* Contracts */}
          <div className="space-y-1">
            <div className="text-[8px] uppercase tracking-wider text-muted-foreground font-semibold px-1">Contracts</div>
            {portfolio.contracts.map(c => {
              const mp = prices[c.contractId] ?? c.entryPrice;
              const pnl = c.status === 'active' ? contractPnl(c, mp) : c.realizedPnl;
              const dir = c.direction === 'long' ? 1 : -1;
              const pctMove = ((mp - c.entryPrice) / c.entryPrice) * dir * 100;
              const tpProg = Math.max(0, Math.min(100, (pctMove / c.tpPct) * 100));
              const slDist = c.slPct + pctMove; // distance from SL trigger
              return (
                <div key={c.contractId + c.entryPrice} className="bg-secondary/30 border border-border rounded p-1.5 text-[9px] font-mono">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-foreground">{c.contract} <span className={c.direction === 'long' ? 'text-accent' : 'text-destructive'}>{c.direction[0].toUpperCase()}</span> {c.leverage}x</span>
                    <span className={pnl >= 0 ? 'text-accent' : 'text-destructive'}>
                      {pnl >= 0 ? '+' : ''}${pnl.toFixed(2)}
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-muted-foreground mt-0.5">
                    <span>{c.status === 'active' ? `mark ${mp.toFixed(4)}` : c.status.toUpperCase()}</span>
                    <span>{pctMove >= 0 ? '+' : ''}{pctMove.toFixed(2)}%</span>
                  </div>
                  {c.status === 'active' && (
                    <div className="mt-1 flex items-center gap-1">
                      <div className="flex-1 h-0.5 bg-secondary rounded overflow-hidden">
                        <div className="h-full bg-accent" style={{ width: `${tpProg}%` }} />
                      </div>
                      <span className="text-[7px] text-muted-foreground">TP{c.tpPct}/SL{c.slPct} · {slDist.toFixed(1)}% to SL</span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Attrition (equity history) */}
          {portfolio.equityHistory.length > 1 && (
            <div>
              <div className="text-[8px] uppercase tracking-wider text-muted-foreground font-semibold px-1 mb-0.5">Portfolio Survival</div>
              <div className="flex items-end gap-0.5 h-10 bg-secondary/20 rounded px-1 py-1">
                {portfolio.equityHistory.slice(-20).map((h, i, arr) => {
                  const max = Math.max(...arr.map(x => x.equity), portfolio.margin);
                  const pct = max > 0 ? (h.equity / max) * 100 : 0;
                  return (
                    <div key={i} className="flex-1 bg-gold/70 rounded-sm min-h-[2px]" style={{ height: `${pct}%` }} title={`$${h.equity.toFixed(2)}`} />
                  );
                })}
              </div>
            </div>
          )}

          {/* Recent reality events */}
          {portfolio.events.length > 0 && (
            <div>
              <div className="text-[8px] uppercase tracking-wider text-muted-foreground font-semibold px-1 mb-0.5">Reality Injection</div>
              <div className="space-y-0.5 max-h-20 overflow-y-auto custom-scrollbar">
                {portfolio.events.slice(0, 6).map((e, i) => (
                  <div key={i} className="text-[9px] font-mono text-muted-foreground px-1 py-0.5 border-l-2 border-gold/40 pl-1.5">
                    <span className={e.delta != null && e.delta < 0 ? 'text-destructive' : e.delta != null && e.delta > 0 ? 'text-accent' : 'text-foreground'}>
                      {e.message}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Liquidation banner */}
          {portfolio.status === 'liquidated' && (
            <div className="bg-destructive/15 border border-destructive/50 rounded p-2 text-[10px]">
              <div className="text-destructive font-bold uppercase tracking-wider text-[9px]">Portfolio Insolvency</div>
              <div className="text-muted-foreground mt-0.5">{portfolio.liquidationReason}</div>
              <div className="text-foreground font-mono mt-1">
                Final equity: $0.00 · Loss: -${portfolio.margin.toFixed(2)}
              </div>
            </div>
          )}

          {/* Action buttons */}
          {portfolio.status === 'active' ? (
            <div className="grid grid-cols-2 gap-1.5">
              <button
                onClick={() => setCloseMode('partial')}
                className="text-[9px] py-1.5 rounded bg-secondary text-foreground hover:bg-secondary/80 uppercase tracking-wider font-semibold border border-border"
              >
                Partial Close
              </button>
              <button
                onClick={() => setCloseMode('full')}
                className="text-[9px] py-1.5 rounded bg-destructive/20 text-destructive border border-destructive/40 hover:bg-destructive/30 uppercase tracking-wider font-semibold"
              >
                Close Portfolio
              </button>
            </div>
          ) : (
            <button
              onClick={() => portfolioActions.dismiss(portfolio.id)}
              className="w-full text-[9px] py-1.5 rounded bg-secondary text-muted-foreground hover:text-foreground uppercase tracking-wider font-semibold"
            >
              Dismiss
            </button>
          )}
        </div>
      )}

      {closeMode && (
        <PortfolioCloseModal
          portfolio={portfolio}
          prices={prices}
          mode={closeMode}
          onClose={() => setCloseMode(null)}
        />
      )}
    </div>
  );
}

function BigStat({ label, value, sub, tone }: { label: string; value: string; sub: string; tone: 'accent' | 'destructive' | 'gold' }) {
  const color = tone === 'accent' ? 'text-accent' : tone === 'destructive' ? 'text-destructive' : 'text-gold';
  return (
    <div className="bg-secondary/40 border border-border rounded p-2">
      <div className="text-[7px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className={`text-[13px] font-mono font-black ${color}`}>{value}</div>
      <div className="text-[7px] text-muted-foreground leading-tight mt-0.5">{sub}</div>
    </div>
  );
}

function Mini({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-secondary/30 rounded px-1.5 py-1">
      <div className="text-[7px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="text-[10px] font-mono font-bold text-foreground">{value}</div>
    </div>
  );
}
